### ISSUE TITLE
Exiting due to signal SIGSEGV

### ISSUE THREAD

**Issue by zielony12** [Serentty/rusty-dos#9]
```
C:\> gcc 
Exiting due to signal SIGSEGV
Page fault at eip=00041381, error=0004
eax=00000000 ebx=0016bba0 ecx=00000001 edx=00000000 esi=001f22b8 edi=0000b078
ebp=001f2298 esp=001f20d0 program=C:\DEVEL\DJGPP\BIN\GCC.EXE
cs: sel=00a7  base=00400000  limit=001fffff
ds: sel=00af   base=00400000  limit=001fffff
es: sel=00af   base=00400000  limit=001fffff
fs: sel=008f   base=000034f0  limit=0000ffff
gs: sel=00bf  base=00000000  limit=0010ffff
ss: sel=00af  base=00400000  limit=001ffffff
App stack: [001f2394..00172394]  Exceptn stack: [00171d9c..0016fe5c]

Call frame traceback EIPs:
  0x00041381
  0x0004080a
  0x0014b108
```
My os: FreeDOS 1.3-rc4,
i have got the package from FreeDOS 1.3 bonus image with additional software and installed using fdimples FreeDOS package manager.

**Comment by Serentty** [comment]
Are you following the procedure from issue #3 to use DJGPP?

**Comment by zielony12** [comment]
> Are you following the procedure from issue #3 to use DJGPP?

what procedure?

**Comment by Serentty** [comment]
Wait—I'm a bit confused. You're running GCC (DJGPP version) here on FreeDOS, and it's crashing. I'm not sure what it has to do with what I'm doing on this repository (trying to get Rust code to run on MS-DOS, admittedly using DJGPP lately). Are you sure you didn't mean to submit this issue to the DJGPP project or the FreeDOS repositories?

**Comment by zielony12** [comment]
@Serentty I will just try to compile the djgpp, thanks for help.
